branch-defaults:
  master:
    environment: ebtest-dev
global:
  application_name: ebtest
  default_ec2_keyname: aws-eb
  default_platform: Node.js
  default_region: ap-southeast-1
  profile: null
  sc: git
